### ISSUE TITLE
KeyError in LT request Validate

### ISSUE THREAD

**Issue by wyrzykow** [TOMToolkit/tom_lt#57] opened 2024-10-11 20:34 UTC
I am testing the LT requests. There is one field there, marked as required, Photometric Yes/No, but there is no possibility on clicking and selecting either of the options. 
<img width="302" alt="image" src="https://github.com/user-attachments/assets/e8ca04e2-15bc-4607-a955-032dd44a4dc2">

When Validating the request form I get the KeyError on the missing Photometric field.

**Comment by jchate6** [comment] 2024-10-15 22:42
This seems to have been caused by an [update to Bootstrap](https://github.com/django-crispy-forms/django-crispy-forms/issues/1174#issuecomment-873309379) that broke the `InlineRadios` widget. More accurately, the ability to use the `InlineRadios` widget in this way was due to a bug that was fixed in an update to Bootstrap.

**Closed** 2024-10-15 22:45 UTC
Labels: bug, User
